### PR TITLE
Fixes sentence

### PR DESCRIPTION
**Pull request by jgarte**

### CODE REVIEW

**Comment by sogaiu** [comment]
The original text looks ok to me.

**Comment by jgarte** [comment]
> The original text looks ok to me.

I think for the original to be gramatically correct then one other fix would be to use the present participle of interact:

> ... property of the table itself but determined by a given piece of code *interacting* with the table ...

A change is required either way for it to be grammatically correct.

**Comment by sogaiu** [comment]
Oh, sorry, I failed to notice "interacts with the table." as part of the original sentence.

I agree the original suggested change makes more sense.

**Comment by technomancy** [comment]
Applied; thanks!

**Pull request closed without merging**
