### PR TITLE
defn - use local or set (not global)

### PR DESCRIPTION
**Pull request by thatismatt**

### CODE REVIEW

**Comment by technomancy** [comment]
Yes; definitely better than making it global. But what if it could behave differently when given a dotted symbol, such that `(defn love.update [dt] ...)` would use `set` instead of `local`?

**Comment by thatismatt** [comment]
That'd be nice, and would avoid this "define & export" dance:
```
(defn a ...)
(defn b ...)
(defn c ...)
{:a a :b b :c c}
```

**Comment by bb010g** [comment]
How's this look?
```
  :defn (fn [name args ...]
    (local form (if (multi-sym? (. name 1))
                    (sym :set)
                    (sym? name)
                    (sym :local)
                    ; else
                    (error "defn: function names must be symbols")))
    (list form name (list (sym :fn) args ...)))
```

**Comment by technomancy** [comment]
@bb010g yeah, that's more or less what I had in mind.

**Comment by thatismatt** [comment]
@bb010g thanks. That's really helpful. I've updated `defn` to now cater for multi-syms too.

**Pull request merged**
