### PR TITLE
Implement pattern matching macro.

### PR DESCRIPTION
**Pull request by technomancy**
Tried to give an overview of how pattern matching works in `reference.md` but I'm not sure how well I explained it; suggestions for improving the clarity are welcome. The test suite has a more thorough list of supported features with examples.

### CODE REVIEW

**Comment by technomancy** [comment]
This still needs work; it gives the wrong result with this:

```lisp
(match [1 2 3] [x y x] :no [x y z] :yes)
```

Needs to do intra-pattern unification, not just unification with existing locals.

**Comment by bakpakin** [comment]
I have had a look at the code, and I think supporting intra-pattern unification can be done by keeping a table of symbols seen already. If a symbol has been seen already while traversing the pattern, we instead check if the value is equal to the previous binding instead of generating a new binding.

This would require that _all_ previous bindings are available to subsequent bindings. Perhaps declaring all bindings up front with local and using set-forcibly! to add bindings would do the trick.

**Comment by technomancy** [comment]
This can be done without set-forcibly!; it's just a new table we can put things in. I've pushed an implementation; you can see the changes to the tests to see how it works.

I also added a special case to allow `_` to be a wildcard which always matches.

I think this is probably ready to merge now; what do you think?

**Comment by bakpakin** [comment]
Perfect, I like the wildcard! I guess set-forcibly wasn't needed at all.

**Pull request merged**
