### PR TITLE
Tweeze tutorial

### PR DESCRIPTION
**Pull request by kenrestivo**
Made some changes to:

1) mention defn
2) Add some notes on strings and colon-keywords earlier
3) Changed formatting of cond to make it a bit clearer what's going on.

### CODE REVIEW

**Comment by technomancy** [comment]
Thanks but the `defn` macro actually got removed before the first release as it's redundant. The `:colon` style strings are mentioned a little further down in the "Back to tables" section.

**Comment by kenrestivo** [comment]
Huh. I'm using the latest fennel from master, and defn is working just fine.

**Comment by dotemacs** [comment]
@kenrestivo 

> Huh. I'm using the latest fennel from master, and defn is working just fine.

I didn't see the `defn` in the tutorial and when I saw your repo that you shared on IRC about coroutines I saw you using it, so I asked about it.

Then this was pointed out to me:

(The third point from the top.)
https://github.com/bakpakin/Fennel/blob/master/changelog.md#010--2018-11-29

**Comment by technomancy** [comment]
Going to close this out but if you have further suggestions for the tutorial I'm happy to discuss.

**Pull request closed without merging**
