### PR TITLE
Fix relative dotdotdot

### PR DESCRIPTION
**Pull request by rktjmp**
The module-name was not getting set when compiling macros, which meant relative-requires from inside that macro would fail because `...` would be `nil`.

We can set the module-name when searching for the macro-module as we do when searching for regular modules.

Fixes srht#110

### CODE REVIEW

**Comment by rktjmp** [comment]
Test failure seems related to `test-macro-traces`, if that runs before the added test, the added test will fail.

You can prove this with the following patch applied to `test/init.lua` to enforce test order:

```diff
@@ -24,8 +24,16 @@ local function testall(suites)
         -- attach test modules (which export k/v tables of test fns) as alists
         local suite = oldfennel.dofile("test/" .. test .. ".fnl",
                                        {useMetadata = true})
+        local tests = {}
         for name, testfn in pairs(suite) do
-            table.insert(instances, {name,testfn})
+          table.insert(tests, {name, testfn})
+        end
+        table.sort(tests, function (a, b)
+          return a[1] > b[1] -- pass test
+          -- return a[1] < b[1] -- fail test
+        end)
+        for i, pair in ipairs(tests) do
+          table.insert(instances, pair)
         end
     end
     return runner:runSuiteByInstances(instances)
```

Not sure if that is a bug with running `test-macro-traces` (plugin hanging around?), plugins in general, or a unintended side effect of this PR.

**Comment by rktjmp** [comment]
Attached test-run log showing that the `test-macro-traces` remains attached to the fennel context, at least somewhere in the stack. There are many tests between `38` and `76` which do not show any `(do)` plugins attached. AFAICT everything should be executed sequentially as the output shows.

```
lua bootstrap/launcher.lua --no-compiler-sandbox --add-fennel-path src/?.fnl --no-metadata --require-as-include --compile src/fennel.fnl > fennel.lua
export LUA_PATH="test/?.lua;./?.lua"; lua test/init.lua 
1..96
# Started on Thu May 26 16:37:05 2022
ok     38	test-macro-fails
[{:do #<function: 0x55ae1489c140>
  :plugin-from "test-macro-traces"
  :versions ["1.1.1" 1]}]
ok     39	test-macro-traces
ok     40	test-names
-- snip
ok     70	test-literal
ok     71	test-lua-module
ok     72	test-macro-path
ok     73	test-macrodebug
ok     74	test-match
ok     75	test-match-try
[{:do #<function: 0x55ae1489c140>
  :plugin-from "test-macro-traces"
  :versions ["1.1.1" 1]}]
not ok 76	test-relative-chained-mac-mod-mac
#   test/macro.fnl:222: Compile error in ./test/relative-chained-mac-mod-mac.fnl:1
#     Compile error in ./test/relative-chained-mac-mod-mac/mac-head.fnl:4
#     bad news
#   
#                          (let [prefix (or (string.match ddd "(.+%.)mac%-head") "")]
#                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   stack traceback:
#   	[C]: in function 'error'
#   	fennel.lua:3374: in function 'fennel.friend.assert-compile'
#   	(...tail calls...)
#   	fennel.lua:4834: in function 'fennel.utils.hook'
#   	fennel.lua:817: in function <fennel.lua:801>
#   	(...tail calls...)
#   	fennel.lua:2683: in function <fennel.lua:2682>
#   	(...tail calls...)
#   	fennel.lua:938: in function <fennel.lua:936>
#   	(...tail calls...)
#   	fennel.lua:2683: in function <fennel.lua:2682>
#   	(...tail calls...)
#   	fennel.lua:938: in function <fennel.lua:936>
#   	(...tail calls...)
#   	fennel.lua:2683: in function <fennel.lua:2682>
#   	(...tail calls...)
#   	fennel.lua:2706: in function <fennel.lua:2704>
#   	(...tail calls...)
#   	...	(skipping 16 levels)
#   	[C]: in function 'pcall'
#   	test/macro.fnl:221: in upvalue 'methodInstance'
#   	test/luaunit.lua:3023: in function <test/luaunit.lua:3023>
#   	[C]: in function 'xpcall'
#   	test/luaunit.lua:3023: in method 'protectedCall'
#   	test/luaunit.lua:3100: in method 'execOneFunction'
#   	test/luaunit.lua:3244: in method 'internalRunSuiteByInstances'
#   	test/luaunit.lua:3431: in function <test/luaunit.lua:3419>
#   	(...tail calls...)
#   	[C]: in function 'pcall'
#   	test/init.lua:61: in main chunk
#   	[C]: in ?
#   
#   (import-macros {: rsym} (.. ... :.mac-head))
#   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   expected: true, actual: false
ok     77	test-relative-macros

-- snip

# Ran 96 tests in 0.505 seconds, 95 successes, 1 failure

```

**Comment by rktjmp** [comment]
Something in the ordering of these tests alters the whole suite state:

```
lua bootstrap/launcher.lua --no-compiler-sandbox --add-fennel-path src/?.fnl --no-metadata --require-as-include --compile src/fennel.fnl > fennel.lua
export LUA_PATH="test/?.lua;./?.lua"; lua test/init.lua 
1..59
# Started on Thu May 26 16:50:36 2022
ok     1	core/test-with-open
ok     2	core/test-nest
ok     3	core/test-method-calls
ok     4	core/test-if
ok     5	core/test-hashfn
ok     6	core/test-functions
ok     7	core/test-fennelview
ok     8	core/test-edge
ok     9	core/test-destructuring
ok     10	core/test-core
ok     11	core/test-conditionals
ok     12	core/test-comparisons
ok     13	core/test-comment
ok     14	core/test-calculations
ok     15	core/test-booleans
ok     16	failures/test-suggestions
ok     17	failures/test-parse-fails
ok     18	failures/test-names
[{:do #<function: 0x5589b51b57f0>
  :plugin-from "test-macro-traces"
  :versions ["1.1.1" 1]}]
ok     19	failures/test-macro-traces
ok     20	failures/test-macro-fails
ok     21	failures/test-macro
ok     22	failures/test-global-fails
ok     23	failures/test-fn-fails
ok     24	failures/test-core-fails
ok     25	failures/test-binding-fails
ok     26	repl/test-sym-completion
ok     27	repl/test-source-offset
ok     28	repl/test-reset
ok     29	repl/test-reload-macros
ok     30	repl/test-reload
ok     31	repl/test-plugins
ok     32	repl/test-options
ok     33	repl/test-no-undocumented
ok     34	repl/test-method-completion
ok     35	repl/test-macro-completion
ok     36	repl/test-locals-saving
ok     37	repl/test-help
ok     38	repl/test-exit
ok     39	repl/test-docstrings
ok     40	repl/test-code
ok     41	repl/test-byteoffset
ok     42	repl/test-apropos
ok     43	macro/test-require-macros
ok     44	macro/test-relative-macros
ok     45	macro/test-relative-chained-mac-mod-mac
ok     46	macro/test-match-try
ok     47	macro/test-match
ok     48	macro/test-macrodebug
ok     49	macro/test-macro-path
ok     50	macro/test-lua-module
ok     51	macro/test-literal
ok     52	macro/test-inline-macros
ok     53	macro/test-import-macros
ok     54	macro/test-expand
ok     55	macro/test-eval-compiler
ok     56	macro/test-doto
ok     57	macro/test-disabled-sandbox-searcher
ok     58	macro/test-arrows
ok     59	macro/test-?.
# Ran 59 tests in 0.354 seconds, 59 successes, 0 failures
```

```
lua bootstrap/launcher.lua --no-compiler-sandbox --add-fennel-path src/?.fnl --no-metadata --require-as-include --compile src/fennel.fnl > fennel.lua
export LUA_PATH="test/?.lua;./?.lua"; lua test/init.lua 
1..59
# Started on Thu May 26 16:50:09 2022
ok     1	core/test-booleans
ok     2	core/test-calculations
ok     3	core/test-comment
ok     4	core/test-comparisons
ok     5	core/test-conditionals
ok     6	core/test-core
ok     7	core/test-destructuring
ok     8	core/test-edge
ok     9	core/test-fennelview
ok     10	core/test-functions
ok     11	core/test-hashfn
ok     12	core/test-if
ok     13	core/test-method-calls
ok     14	core/test-nest
ok     15	core/test-with-open
ok     16	failures/test-binding-fails
ok     17	failures/test-core-fails
ok     18	failures/test-fn-fails
ok     19	failures/test-global-fails
ok     20	failures/test-macro
ok     21	failures/test-macro-fails
[{:do #<function: 0x560334bf86d0>
  :plugin-from "test-macro-traces"
  :versions ["1.1.1" 1]}]
ok     22	failures/test-macro-traces
ok     23	failures/test-names
ok     24	failures/test-parse-fails
ok     25	failures/test-suggestions
ok     26	repl/test-apropos
ok     27	repl/test-byteoffset
ok     28	repl/test-code
ok     29	repl/test-docstrings
ok     30	repl/test-exit
ok     31	repl/test-help
ok     32	repl/test-locals-saving
ok     33	repl/test-macro-completion
ok     34	repl/test-method-completion
ok     35	repl/test-no-undocumented
ok     36	repl/test-options
ok     37	repl/test-plugins
ok     38	repl/test-reload
ok     39	repl/test-reload-macros
ok     40	repl/test-reset
ok     41	repl/test-source-offset
ok     42	repl/test-sym-completion
ok     43	macro/test-?.
ok     44	macro/test-arrows
ok     45	macro/test-disabled-sandbox-searcher
ok     46	macro/test-doto
ok     47	macro/test-eval-compiler
ok     48	macro/test-expand
ok     49	macro/test-import-macros
ok     50	macro/test-inline-macros
ok     51	macro/test-literal
ok     52	macro/test-lua-module
ok     53	macro/test-macro-path
ok     54	macro/test-macrodebug
ok     55	macro/test-match
ok     56	macro/test-match-try
[{:do #<function: 0x560334bf86d0>
  :plugin-from "test-macro-traces"
  :versions ["1.1.1" 1]}]
not ok 57	macro/test-relative-chained-mac-mod-mac
#   test/macro.fnl:222: Compile error in ./test/relative-chained-mac-mod-mac.fnl:1
#     Compile error in ./test/relative-chained-mac-mod-mac/mac-head.fnl:4
#     bad news
#   
#                          (let [prefix (or (string.match ddd "(.+%.)mac%-head") "")]
#                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   stack traceback:
#   	[C]: in function 'error'
#   	fennel.lua:3374: in function 'fennel.friend.assert-compile'
#   	(...tail calls...)
#   	fennel.lua:4834: in function 'fennel.utils.hook'
#   	fennel.lua:817: in function <fennel.lua:801>
#   	(...tail calls...)
#   	fennel.lua:2683: in function <fennel.lua:2682>
#   	(...tail calls...)
#   	fennel.lua:938: in function <fennel.lua:936>
#   	(...tail calls...)
#   	fennel.lua:2683: in function <fennel.lua:2682>
#   	(...tail calls...)
#   	fennel.lua:938: in function <fennel.lua:936>
#   	(...tail calls...)
#   	fennel.lua:2683: in function <fennel.lua:2682>
#   	(...tail calls...)
#   	fennel.lua:2706: in function <fennel.lua:2704>
#   	(...tail calls...)
#   	...	(skipping 16 levels)
#   	[C]: in function 'pcall'
#   	test/macro.fnl:221: in upvalue 'methodInstance'
#   	test/luaunit.lua:3023: in function <test/luaunit.lua:3023>
#   	[C]: in function 'xpcall'
#   	test/luaunit.lua:3023: in method 'protectedCall'
#   	test/luaunit.lua:3100: in method 'execOneFunction'
#   	test/luaunit.lua:3244: in method 'internalRunSuiteByInstances'
#   	test/luaunit.lua:3431: in function <test/luaunit.lua:3419>
#   	(...tail calls...)
#   	[C]: in function 'pcall'
#   	test/init.lua:61: in main chunk
#   	[C]: in ?
#   
#   (import-macros {: rsym} (.. ... :.mac-head))
#   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   expected: true, actual: false
ok     58	macro/test-relative-macros
ok     59	macro/test-require-macros
# Ran 59 tests in 0.376 seconds, 58 successes, 1 failure
```

**Comment by rktjmp** [comment]
Seems that you must run `repl.fnl#test-sym-completion` to fix the test state, specifically the final `send` in that test:

```fennel
(fn test-sym-completion []
  (let [(send comp) (wrap-repl {:env (collect [k v (pairs _G)] (values k v))})]
    ;; ... snip
    ;; running this line clears any previously attached `:do` plugins 
    (let [(ok msg) (pcall send ",complete ]")]
       (l.assertTrue ok "shouldn't kill the repl on a parse error"))
    ))
```

Reducing the test suites to a minimal list and enforcing a know run order:

```
  "core", -- seems required for some basic tests to load
  "failures", -- test suite with offensive `test-macro-traces` test
  "repl", -- test suite that can clear the attached plugins
  "macro", -- test suite that fails because of `test-macro-traces` attached test
```

We can see a successful run with the `,complete [` expression sent to the repl:

```
lua bootstrap/launcher.lua --no-compiler-sandbox --add-fennel-path src/?.fnl --no-metadata --require-as-include --compile src/fennel.fnl > fennel.lua
export LUA_PATH="test/?.lua;./?.lua"; lua test/init.lua 
Lua 5.4
1..59
# Started on Thu May 26 18:14:36 2022
ok     1	core/test-with-open
ok     2	core/test-nest
ok     3	core/test-method-calls
ok     4	core/test-if
ok     5	core/test-hashfn
ok     6	core/test-functions
ok     7	core/test-fennelview
ok     8	core/test-edge
ok     9	core/test-destructuring
ok     10	core/test-core
ok     11	core/test-conditionals
ok     12	core/test-comparisons
ok     13	core/test-comment
ok     14	core/test-calculations
ok     15	core/test-booleans
ok     16	failures/test-suggestions
ok     17	failures/test-parse-fails
ok     18	failures/test-names
[{:do #<function: 0x5577a920fe20>
  :plugin-from "test-macro-traces"
  :versions ["1.1.1" 1]}]
ok     19	failures/test-macro-traces
ok     20	failures/test-macro-fails
ok     21	failures/test-macro
ok     22	failures/test-global-fails
ok     23	failures/test-fn-fails
ok     24	failures/test-core-fails
ok     25	failures/test-binding-fails
ok     26	repl/test-sym-completion
ok     27	repl/test-source-offset
ok     28	repl/test-reset
ok     29	repl/test-reload-macros
ok     30	repl/test-reload
ok     31	repl/test-plugins
ok     32	repl/test-options
ok     33	repl/test-no-undocumented
ok     34	repl/test-method-completion
ok     35	repl/test-macro-completion
ok     36	repl/test-locals-saving
ok     37	repl/test-help
ok     38	repl/test-exit
ok     39	repl/test-docstrings
ok     40	repl/test-code
ok     41	repl/test-byteoffset
ok     42	repl/test-apropos
ok     43	macro/test-require-macros
ok     44	macro/test-relative-macros
ok     45	macro/test-relative-chained-mac-mod-mac
ok     46	macro/test-match-try
ok     47	macro/test-match
ok     48	macro/test-macrodebug
ok     49	macro/test-macro-path
ok     50	macro/test-lua-module
ok     51	macro/test-literal
ok     52	macro/test-inline-macros
ok     53	macro/test-import-macros
ok     54	macro/test-expand
ok     55	macro/test-eval-compiler
ok     56	macro/test-doto
ok     57	macro/test-disabled-sandbox-searcher
ok     58	macro/test-arrows
ok     59	macro/test-?.
# Ran 59 tests in 0.350 seconds, 59 successes, 0 failures
```

Then commenting out the `,complete ]` line:

```fennel
(fn test-sym-completion []
  (let [(send comp) (wrap-repl {:env (collect [k v (pairs _G)] (values k v))})]
    ;; ... snip
    ;; disable repl parse error test
    ; (let [(ok msg) (pcall send ",complete ]")]
    ;   (l.assertTrue ok "shouldn't kill the repl on a parse error"))
    ))
```

We then see the failure with the erroneously attached `:do` plugin.

```

lua bootstrap/launcher.lua --no-compiler-sandbox --add-fennel-path src/?.fnl --no-metadata --require-as-include --compile src/fennel.fnl > fennel.lua
export LUA_PATH="test/?.lua;./?.lua"; lua test/init.lua 
Lua 5.4
1..59
# Started on Thu May 26 18:15:59 2022
ok     1	core/test-with-open
ok     2	core/test-nest
ok     3	core/test-method-calls
ok     4	core/test-if
ok     5	core/test-hashfn
ok     6	core/test-functions
ok     7	core/test-fennelview
ok     8	core/test-edge
ok     9	core/test-destructuring
ok     10	core/test-core
ok     11	core/test-conditionals
ok     12	core/test-comparisons
ok     13	core/test-comment
ok     14	core/test-calculations
ok     15	core/test-booleans
ok     16	failures/test-suggestions
ok     17	failures/test-parse-fails
ok     18	failures/test-names
[{:do #<function: 0x5594251e6f10>
  :plugin-from "test-macro-traces"
  :versions ["1.1.1" 1]}]
ok     19	failures/test-macro-traces
ok     20	failures/test-macro-fails
ok     21	failures/test-macro
ok     22	failures/test-global-fails
ok     23	failures/test-fn-fails
ok     24	failures/test-core-fails
ok     25	failures/test-binding-fails
ok     26	repl/test-sym-completion
ok     27	repl/test-source-offset
ok     28	repl/test-reset
ok     29	repl/test-reload-macros
ok     30	repl/test-reload
ok     31	repl/test-plugins
ok     32	repl/test-options
ok     33	repl/test-no-undocumented
ok     34	repl/test-method-completion
ok     35	repl/test-macro-completion
ok     36	repl/test-locals-saving
ok     37	repl/test-help
ok     38	repl/test-exit
ok     39	repl/test-docstrings
ok     40	repl/test-code
ok     41	repl/test-byteoffset
ok     42	repl/test-apropos
ok     43	macro/test-require-macros
ok     44	macro/test-relative-macros
[{:do #<function: 0x5594251e6f10>
  :plugin-from "test-macro-traces"
  :versions ["1.1.1" 1]}]
not ok 45	macro/test-relative-chained-mac-mod-mac
#   test/macro.fnl:222: Compile error in ./test/relative-chained-mac-mod-mac.fnl:1
#     Compile error in ./test/relative-chained-mac-mod-mac/mac-head.fnl:4
#     bad news
#   
#                          (let [prefix (or (string.match ddd "(.+%.)mac%-head") "")]
#                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   stack traceback:
#   	[C]: in function 'error'
#   	fennel.lua:3374: in function 'fennel.friend.assert-compile'
#   	(...tail calls...)
#   	fennel.lua:4834: in function 'fennel.utils.hook'
#   	fennel.lua:817: in function <fennel.lua:801>
#   	(...tail calls...)
#   	fennel.lua:2683: in function <fennel.lua:2682>
#   	(...tail calls...)
#   	fennel.lua:938: in function <fennel.lua:936>
#   	(...tail calls...)
#   	fennel.lua:2683: in function <fennel.lua:2682>
#   	(...tail calls...)
#   	fennel.lua:938: in function <fennel.lua:936>
#   	(...tail calls...)
#   	fennel.lua:2683: in function <fennel.lua:2682>
#   	(...tail calls...)
#   	fennel.lua:2706: in function <fennel.lua:2704>
#   	(...tail calls...)
#   	...	(skipping 16 levels)
#   	[C]: in function 'pcall'
#   	test/macro.fnl:221: in upvalue 'methodInstance'
#   	test/luaunit.lua:3023: in function <test/luaunit.lua:3023>
#   	[C]: in function 'xpcall'
#   	test/luaunit.lua:3023: in method 'protectedCall'
#   	test/luaunit.lua:3100: in method 'execOneFunction'
#   	test/luaunit.lua:3244: in method 'internalRunSuiteByInstances'
#   	test/luaunit.lua:3431: in function <test/luaunit.lua:3419>
#   	(...tail calls...)
#   	[C]: in function 'pcall'
#   	test/init.lua:61: in main chunk
#   	[C]: in ?
#   
#   (import-macros {: rsym} (.. ... :.mac-head))
#   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   expected: true, actual: false
ok     46	macro/test-match-try
ok     47	macro/test-match
ok     48	macro/test-macrodebug
ok     49	macro/test-macro-path
ok     50	macro/test-lua-module
ok     51	macro/test-literal
ok     52	macro/test-inline-macros
ok     53	macro/test-import-macros
ok     54	macro/test-expand
ok     55	macro/test-eval-compiler
ok     56	macro/test-doto
ok     57	macro/test-disabled-sandbox-searcher
ok     58	macro/test-arrows
ok     59	macro/test-?.
# Ran 59 tests in 0.379 seconds, 58 successes, 1 failure
```

`test-sym-completion` clones `_G` into its own `:env`. Perhaps when the completion crashes, something is is refreshed that that side effects back up to the test context which clears the plugin out of future tests?

**Comment by technomancy** [comment]
Sorry for the delay on this; I broke my hand and so haven't been keeping up on things. It looks like the actual fix was quite quick, but getting the functionality tested involved fixing some nasty bugs in the test suite, so I appreciate the work you did to track that down. It's definitely an oversight that the macro searcher behaved differently from the regular searcher in this regard.

**Comment by technomancy** [comment]
Merged!

**Pull request closed without merging**
