### PR TITLE
tutorial: note on naming identifiers

### PR DESCRIPTION
**Pull request by uvtc**
For #314 .

More complete details could go into the reference later on.

### CODE REVIEW

**Comment by technomancy** [comment]
Thanks; this looks good, except it refers to the destructuring section when mentioning underscore, but the destructuring section doesn't mention anything about underscores. Did you mean to add another section there?

**Comment by uvtc** [comment]
No, I didn't mean to add another section for this. I see that destructuring is covered in the "back to tables just for a bit" section, but there's no destructing subsection, so I just mentioned it but didn't provide a link. I think there needs to be *something* after that comment about using underscores, otherwise the reader will think "variables you don't intend to use?? Bah, that makes no sense", but I don't want to throw out fancy terminology without at least a little tidbit to let the reader know, "don't worry, we'll get to that in a bit".

**Comment by technomancy** [comment]
I guess I'm still not following; I don't see what the connection is between underscores and destructuring. Underscores are used anywhere that you can bind a value, regardless of whether it's being destructured or not. For example, there is no destructuring here:

```
(fn [a _ msg]
  (when a
    (print msg)))
```

Nor is there here:

```
(let [f (io.open filename)
      _ (assert f)
      contents (f:read :*all)]
  (consume contents))
```

**Comment by uvtc** [comment]
Ah! Whoops. I see what you mean. Ok, removed that little bit.

**Comment by technomancy** [comment]
Cool; thanks!

**Pull request merged**
