### PR TITLE
Make `fennel --eval` print all return values, fix test-arg

### PR DESCRIPTION
**Pull request by emmyposs**
makes dosafely return the same number of values as the function it calls.
fixes test-arg not matching correct output.

this probably?? could use a test for the multiple return from dosafely, id be willing to implement one if yall could give some pointers

### CODE REVIEW

**Comment by technomancy** [comment]
Thanks for this patch.

Since `dosafely` is an internal function to the launcher, testing it directly isn't important. As far as I can tell, the only place the return value of `dosafely` is relevant is for `--eval`, right? In that case we can test it in `test/cli.fnl` which is where the other launcher features are tested.

I'm not clear on why the addition of the `pack` function is necessary here. It seems that the same effect could be achieved by just wrapping the `xpcall` in a table, right?

**Comment by technomancy** [comment]
Sorry; I realized my fix for the test conflicts with this so you might want to rebase on main and just include the one launcher commit.

**Comment by emmyposs** [comment]
rebased, added a test for multiple return values.

> [...] It seems that the same effect could be achieved by just wrapping the xpcall in a table, right?

that is mostly correct for PUC lua, but not luajit - luajit stops counting at the first nil regardless of how the table is created, so the number of values needs to be saved.
(note 'mostly correct for PUC lua' - it also stops at the first nil, but only if the table was created from a literal whose last 2 values are nils.)

**Comment by technomancy** [comment]
> that is mostly correct for PUC lua, but not luajit - luajit stops counting at the first nil regardless of how the table is created, so the number of values needs to be saved.

> print(unpack({5, nil, nil, nil, 8, nil, nil}))
> 5

Good lord; that's deeply bizarre and somewhat frustrating. Thanks for the heads up; I had no idea.

I've merged your changes; thanks! (github has a bug where it marks this as closed despite the changes being merged because they were merged outside github)

**Pull request closed without merging**
