### PR TITLE
Add --compile-binary command to make standalone binaries

### PR DESCRIPTION
**Pull request by technomancy**
This is still super experimental!!!

Edit: renamed it from `--compile-static` to `--compile-binary` to reflect that it can be used with or without static linking.

### CODE REVIEW

**Comment by technomancy** [comment]
I think this is ready for review. One question: does this merit its own module, or should it just be part of `launcher.fnl`? I'm leaning a bit towards keeping it separate to emphasize the fact that it's extremely untested and likely to be volatile, but maybe that's unnecessary.

**Comment by jaawerth** [comment]
All else being equal, all else being equal I'd opt to keep it separate for *now*, only so we can play around with it and see if we want to change how it's configured a bit; even with a warning, it we add it as a supported flag to the standalone, some people may end up getting used to it being there so any future changes to the flags/env vars would be a breaking change, experimental or not. 0.4.1 is also primarily a bugfix release, and even though this is purely additive it might be nice if we stuck with stabilizing the core of 0.4.1 rather than risking future complications?

On the other hand, it IS purely additive so as long as we triple-check for side effects in the standalone build, so if you really want it in there I don't feel strongly enough about it to fight you on it :wink:.

As for review, if we *do* end up including it as part of `launcher.fnl` I'd just ask that we wait on merging this until a fix for #278 is merged, so we can test the standalone launcher for quirks free of complications with and without `fennelstatic`.

**Comment by jaawerth** [comment]
Also, this is super cool!

**Comment by technomancy** [comment]
> as long as we triple-check for side effects in the standalone build

This patch touches 4 files: `.gitignore`, `Makefile`, the new `fennelbinary` module, and `launcher.fnl`; so `fennel.lua` is unaffected. The only changes to `launcher.fnl` are to handle `--compile-binary` at the very end, and the help text.

>  if we do end up including it as part of launcher.fnl I'd just ask that we wait on a full review/merge of this until a fix for #278 is merged

Yep, good call.

**Comment by technomancy** [comment]
I tidied up the C shim bits into one longer string and replaced the Lua loader shim with a Fennel macro to reduce the amount of code-in-a-string we rely upon. This is a very strange piece of code because we don't want to run the macro, we just want to take the compiled Lua as a string that comes from the macroexpansion and splice it into the C code after hex-encoding it.

Currently there's no way to do this, so I added a flag to `macrodebug` which returns the expanded form string instead of printing it.

I was also considering keeping the C shim bits in a separate file and loading it in at compile time but I haven't done that yet.

**Pull request merged**
